### ISSUE TITLE
📌 KerasFuse: Current Features, High-Priority Items, and Contributing Opportunities

### ISSUE THREAD

**Issue by TarikKaanKoc** [ayyucedemirbas/KerasFuse#11]
Hello KerasFuse Team! @ayyucedemirbas  @onuralpszr  👋🏼 

I am interested in contributing to this project and would like to learn more about your future plans and goals. What features are you currently working on? Which features or fixes are considered high-priority? And how do you envision a contributor like myself assisting with the project?

Additionally Id like to gain a deeper understanding of the overall aims and vision of the project. I heard that KerasFuse is being positioned as an alternative to MONAI and Id like to learn more about this. What are the long-term objectives for this project and what steps do you think need to be taken to achieve these goals???

Thank you for your assistance and your time.
TKK 😊

**Comment by onuralpszr** [comment]
@TKaanKoc  hello, we were talking about making a "milestone" list for project and based on we can move forward easier and we can also determine task list as well. I Just recently also add "https://github.com/ayyucedemirbas/KerasFuse/blob/main/CONTRIBUTING.md" section for setup dev part. That gives at least idea about how to get started it. 

I wanted answer this quicker but I did not want to before talking Ayyuce so now I can give bit more clearer as well. But general idea is adding more feature of MONAI but based on keras/tensorflow.

**Comment by TarikKaanKoc** [comment]
Thanks for your response and support @onuralpszr
