### ISSUE TITLE
KerasFuse : Contributing to this  project and how to setup the repository before working with it

### ISSUE THREAD

**Issue by ash-01xor** [ayyucedemirbas/KerasFuse#12]
Hey KerasFuse team @onuralpszr  @ayyucedemirbas

I would like to contribute to the project and before contributing to the project I would like to have detailed information regarding the way I might need to contribute and also how to setup before working on it.

I believe the documentation doesn't give a clear idea regarding how to setup the repository and work with it.

Thank you for your assistance and your time

**Comment by onuralpszr** [comment]
Hello @ash-01xor  thank you for your contrib and for your question I made better 

https://github.com/ayyucedemirbas/KerasFuse/blob/main/CONTRIBUTING.md

For that, I hope that will answer your question.  If you see any problem please let us know I will try to make it bit more clearer.  If you think that is your answer please feel free to close issue as well.

**Comment by ash-01xor** [comment]
Well, thanks for responding. I got to see it today, and it did help in contributing to the repository.
